---
driver:
  name: docker
  use_sudo: false
  privileged: true
provisioner:
  #name: puppet_apply
  name: chef_zero
  mainfests_path: manifests
  modules_path: modules
  require_chef_for_busser: true
  require_chef_omnibus: true
  require_puppet_collections: false
  require_puppet_omnibus: false
  require_puppet_repo: false
  update_package_repos: false
platforms:
  - name: ubuntu
    driver_config:
     image: laboshin/centos
     hostname: chef.sucks
suites:
  - name: default
    run_list:
      - recipe[yum-epel]
      - recipe[example5::default]
    attributes: {}
      
